export const movieData = {
  dates: {
    maximum: "2024-05-22",
    minimum: "2024-04-10",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "진화한 유인원과 퇴화된 인간들이 살아가는 땅. 유인원 리더 프록시무스는 완전한 군림을 위해 인간들을 사냥하며 자신의 제국을 건설한다. 한편, 또 다른 유인원 노아는 우연히 숨겨진 과거의 이야기와 시저의 가르침을 듣게 되고 인간과 유인원이 함께 할 새로운 세상을 꿈꾼다. 어느 날 그의 앞에 나타난 의문의 한 인간 소녀. 노아는 그녀와 함께 자유를 향한 여정을 시작하게 되는데…",
      popularity: 1802.132,
      poster_path: "/plNOSbqkSuGEK2i15A5btAXtB7t.jpg",
      release_date: "2024-05-08",
      title: "혹성탈출: 새로운 시대",
      video: false,
      vote_average: 7.202,
      vote_count: 386,
    },
    {
      adult: false,
      backdrop_path: "/wODqakS0jinTUECNS6n4VomQbew.jpg",
      genre_ids: [14, 12, 35],
      id: 967847,
      original_language: "en",
      original_title: "Ghostbusters: Frozen Empire",
      overview:
        "무더운 여름의 뉴욕의 어느 날, 고대 유물 속 깨어난 데스칠로 인해 정체불명의 냉기가 몰려오고 마침내 도시는 얼어붙고 만다. 유령을 퇴치하는 그루버슨과 라이즈 버스터즈 멤버들은 얼어붙은 세상을 깨부수기 위해 유령 군단을 쫓기 시작하는데…",
      popularity: 933.069,
      poster_path: "/mGzSIfzmcf9H91DS06cnka1SYrP.jpg",
      release_date: "2024-04-17",
      title: "고스트버스터즈: 오싹한 뉴욕",
      video: false,
      vote_average: 6.755,
      vote_count: 734,
    },
    {
      adult: false,
      backdrop_path: "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "마침내 내면의 평화… 냉면의 평화…가 찾아왔다고 믿는 용의 전사 ‘포’ 이젠 평화의 계곡의 영적 지도자가 되고, 자신을 대신할 후계자를 찾아야만 한다. “이제 용의 전사는 그만둬야 해요?” 용의 전사로의 모습이 익숙해지고 새로운 성장을 하기보다 지금 이대로가 좋은 ‘포’ 하지만 모든 쿵푸 마스터들의 능력을 그대로 복제하는 강력한 빌런 ‘카멜레온’이 나타나고 그녀를 막기 위해 정체를 알 수 없는 쿵푸 고수 ‘젠’과 함께 모험을 떠나게 되는데… 포는 가장 강력한 빌런과 자기 자신마저 뛰어넘고 진정한 변화를 할 수 있을까?",
      popularity: 940.647,
      poster_path: "/1ZNOOMmILNUzVYbzG1j7GYb5bEV.jpg",
      release_date: "2024-04-10",
      title: "쿵푸팬더 4",
      video: false,
      vote_average: 7.125,
      vote_count: 1672,
    },
    {
      adult: false,
      backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      genre_ids: [27, 53],
      id: 1111873,
      original_language: "en",
      original_title: "Abigail",
      overview:
        "오직 돈을 위해서 업계 최고들로만 모인 납치범들. 정체를 알 수 없는 거부의 딸이자 평범한 소녀 ‘애비게일’을 납치하고, 24시간 동안 저택에서 그녀를 감시하고 거액의 돈을 받기로 한다. 하지만 평범한 소녀 ‘애비게일’은 발레리나 뱀파이어였고 오히려 납치범들은 역으로 저택에 갇혀 그녀의 장난감과 먹이가 되었다. 납치범들은 이제 24시간 안에 살기 위해 저택을 탈출해야 한다.",
      popularity: 768.599,
      poster_path: "/dRCVYbOjhMNghBQgHuqthG5iLH.jpg",
      release_date: "2024-05-15",
      title: "애비게일",
      video: false,
      vote_average: 6.93,
      vote_count: 409,
    },
    {
      adult: false,
      backdrop_path: "/vWzJDjLPmycnQ42IppEjMpIhrhc.jpg",
      genre_ids: [16, 35, 10751],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "세상귀찮 집냥이, 바쁘고 험난한 세상에 던져졌다! 집사 ‘존’과 반려견 ‘오디’를 기르며 평화로운 나날을 보내던 집냥이 ‘가필드’. 어느 날, 험악한 길냥이 무리에게 납치당해 냉혹한 거리로 던져진다. 돌봐주는 집사가 없는 집 밖 세상은 너무나도 정신없게 돌아가고 길에서 우연히 다시 만난 아빠 길냥이 ‘빅’은 오히려 ‘가필드’를 위기에 빠지게 하는데… 험난한 세상, 살아남아야 한다!",
      popularity: 597.778,
      poster_path: "/57g3pHYi3p0JNVO1LkcyYbeMDBf.jpg",
      release_date: "2024-05-15",
      title: "가필드 더 무비",
      video: false,
      vote_average: 6.712,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/jTWllMddJzCb7hBVNZICtgKhYM9.jpg",
      genre_ids: [35, 14, 10751, 16],
      id: 639720,
      original_language: "en",
      original_title: "IF",
      overview:
        "상상의 친구 ‘이프’를 볼 수 있는 능력을 지닌 한 소녀가 아이들에게 잊혀졌던 ‘이프’를 다시 되찾아주기 위해 마법 같은 모험을 시작하는 이야기를 그린 영화",
      popularity: 396.496,
      poster_path: "/9GAOhSzXjXJR4AxYCa2AMzMGPVg.jpg",
      release_date: "2024-05-15",
      title: "이프: 상상의 친구",
      video: false,
      vote_average: 7.3,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/shrwC6U8Bkst9T9J7fr1A50n6x6.jpg",
      genre_ids: [878, 28, 12],
      id: 786892,
      original_language: "en",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "문명 붕괴 45년 후, 황폐해진 세상에 무참히 던져진 '퓨리오사'가 고향으로 돌아가기 위해 자신의 인생 전부를 걸고 떠나는 거대한 여정을 그린 액션 블록버스터",
      popularity: 420.744,
      poster_path: "/zaUFDdJidS4Nyyd6jb2Ok3Kq4Vo.jpg",
      release_date: "2024-05-22",
      title: "퓨리오사: 매드맥스 사가",
      video: false,
      vote_average: 8.1,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "어드벤처 레이싱 팀 주장 ‘마이클’은 최고로 힘든 지형과 날씨의 도미니카 공화국에서 700KM를 질주해야 한다! 여러 단계를 통과하던 중, '마이클' 앞에 떠돌이 개 '아서'가 나타나고 그의 팀을 따라다니기 시작하는데, '아서'를 포기해야만 우승 할 수 있는 상황..!  마지막 도전! 우승을 놓칠 수 없는 경기! ‘’아서’와 끝가지 함께 할 수 있을까?",
      popularity: 251.026,
      poster_path: "/a9B0PGRIhmOGRmpKdNR46id30Pt.jpg",
      release_date: "2024-04-17",
      title: "아서",
      video: false,
      vote_average: 6.829,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
      genre_ids: [28, 35],
      id: 746036,
      original_language: "en",
      original_title: "The Fall Guy",
      overview:
        "잠수 이별을 택하고 후회뿐인 날을 보내던 스턴트맨 ‘콜트’(라이언 고슬링) 영화감독이 된 전 여친 ‘조디’(에밀리 블런트)의 촬영장에 복귀하며 아련한 재회를 기대했지만… 갑자기 주연배우가 사라지고 콜트는 우선 그부터 찾아야만 한다! \u003C데드풀 2\u003E 감독이 말아주는 코미디, 액션, 로맨스 장르 풀코스 액션도 터지고, 사랑도 터지고, 웃음도 터진다!",
      popularity: 245.962,
      poster_path: "/aUZ176q7ldMaPLYVnmaFWK4CApE.jpg",
      release_date: "2024-05-01",
      title: "스턴트맨",
      video: false,
      vote_average: 7.435,
      vote_count: 393,
    },
    {
      adult: false,
      backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
      genre_ids: [10749, 18],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        "스타급의 인기를 누리던 테니스 천재 타시는 부상으로 인해 더 이상 선수 생활을 하지 못하고 지금은 남편 아트의 코치를 맡고 있다. 연패 슬럼프에서 빠져나오지 못하는 아트를 챌린저급 대회에 참가시킨 타시는 남편과 둘도 없는 친구 사이이자 자신의 전 남친인 패트릭을 다시 만나게 된다. 선 넘는 세 남녀의 아슬아슬한 관계는 테니스 코트 밖에서 더욱 격렬하게 이어지는데… 결승전 D-DAY, 가장 매혹적인 랠리가 시작된다!",
      popularity: 311.06,
      poster_path: "/iUDG0gsPZxNm9IOLqpIUZiUMVMZ.jpg",
      release_date: "2024-04-24",
      title: "챌린저스",
      video: false,
      vote_average: 7.408,
      vote_count: 525,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "1977년 핼러윈 전날 밤, 시청률을 위해서라면 일단 틀고 보는 방송국 놈들 때문에 누구도 예상하지 못한 방송사고 발생! 그리고 마침내 미국 전역을 충격에 빠트렸던 그날 밤의 생방송 악마와의 토크쇼 녹화영상이 최근에 발견됐는데… 47년간 숨겨진, 절대 생중계돼서는 안 될 최악의 토크쇼가 마침내 공개된다, 그동안 공개되지 않은 비하인드 영상과 함께!",
      popularity: 197.514,
      poster_path: "/5nUu9y8hQtmW4Qt5GWZZATCjFnN.jpg",
      release_date: "2024-05-08",
      title: "악마와의 토크쇼",
      video: false,
      vote_average: 7.318,
      vote_count: 357,
    },
    {
      adult: false,
      backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "촉망받는 은행 간부 앤디 듀프레인은 아내와 그녀의 정부를 살해했다는 누명을 쓴다. 주변의 증언과 살해 현장의 그럴듯한 증거들로 그는 종신형을 선고받고 악질범들만 수용한다는 지옥같은 교도소 쇼생크로 향한다. 인간 말종 쓰레기들만 모인 그곳에서 그는 이루 말할 수 없는 억압과 짐승보다 못한 취급을 당한다. 그러던 어느 날, 간수의 세금을 면제받게 해 준 덕분에 그는 일약 교도소의 비공식 회계사로 일하게 된다. 그 와중에 교도소 소장은 죄수들을 이리저리 부리면서 검은 돈을 긁어 모으고 앤디는 이 돈을 세탁하여 불려주면서 그의 돈을 관리하는데...",
      popularity: 151.357,
      poster_path: "/qV9BQZdiM8foEzDz0Ag5hGWE5qM.jpg",
      release_date: "1995-01-28",
      title: "쇼생크 탈출",
      video: false,
      vote_average: 8.705,
      vote_count: 26172,
    },
    {
      adult: false,
      backdrop_path: "/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg",
      genre_ids: [16, 18],
      id: 1012201,
      original_language: "ja",
      original_title: "劇場版ハイキュー!! ゴミ捨て場の決戦",
      overview:
        "봄철 고교 배구대회 미야기현 대표 결정전. 1회전과 2회전에서 우승 후보를 차례로 꺾은 카라스노 고등학교는 마침내 3회전에서 인연의 라이벌 네코마 고등학교와 맞붙게 된다. 공식 경기에서 처음으로 대결하는 두 고등학교, 통칭 까마귀 VS 고양이 ‘쓰레기장의 결전’. 약속의 땅에서 ‘한 번 더’가 없는 싸움이 드디어 시작된다!",
      popularity: 86.205,
      poster_path: "/d0jCRbTdJPEvGaboeZ3fvCUVrNT.jpg",
      release_date: "2024-05-15",
      title: "극장판 하이큐!! 쓰레기장의 결전",
      video: false,
      vote_average: 8.7,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/mO9oOVXM8tTlC11VFM4FBBNnL3f.jpg",
      genre_ids: [80, 28, 18],
      id: 1017163,
      original_language: "ko",
      original_title: "범죄도시 4",
      overview:
        "신종 마약 사건 3년 뒤, 괴물형사 마석도와 서울 광수대는 배달앱을 이용한 마약 판매 사건을 수사하던 중 수배 중인 앱 개발자가 필리핀에서 사망한 사건이 대규모 온라인 불법 도박 조직과 연관되어 있음을 알아낸다. 필리핀에 거점을 두고 납치, 감금, 폭행, 살인 등으로 대한민국 온라인 불법 도박 시장을 장악한 특수부대 용병 출신의 빌런 백창기와 한국에서 더 큰 판을 짜고 있는 IT업계 천재 CEO 장동철. 마석도는 더 커진 판을 잡기 위해 장이수에게 뜻밖의 협력을 제안하고 광역수사대는 물론, 사이버수사대까지 합류해 범죄를 소탕하기 시작하는데…",
      popularity: 75.846,
      poster_path: "/h1YarEjeYurkAwXgfY1RDMVCiin.jpg",
      release_date: "2024-04-24",
      title: "범죄도시 4",
      video: false,
      vote_average: 8.2,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/j11RoLbvHGmJsBHcKqvbZxc5drh.jpg",
      genre_ids: [18, 28, 53],
      id: 1053592,
      original_language: "es",
      original_title: "Todos los nombres de Dios",
      overview:
        "공항에서 손님을 기다리던 택시 운전사 산티, 일순간 공항은 폭탄 테러로 인해 혼비백산 상태가 되고 산티는 그곳에서 테러리스트인 함자에 의해 인질로 잡히게 된다. 산티는 테러리스트에 의해 움직임을 멈추면 폭탄이 폭발해버리는 위험천만한 조끼를 입고 마드리드 중심부를 걸어 다니는 인간 폭탄이 되는데…",
      popularity: 62.225,
      poster_path: "/kx3X00Q1XSozAA60gpVFCVxMNQm.jpg",
      release_date: "2024-04-17",
      title: "올 더 네임즈 오브 갓",
      video: false,
      vote_average: 6.399,
      vote_count: 89,
    },
    {
      adult: false,
      backdrop_path: "/6uKXrsdguwZrtG5BL1wBHvxWs3Z.jpg",
      genre_ids: [28, 80, 53],
      id: 557946,
      original_language: "en",
      original_title: "Last Looks",
      overview:
        "홀로 산에 있는 트레일러에 은둔하고 있는 전직 형사 찰리 왈도에게, 어느 날 전 연인인 로레나가 찾아온다.  그녀의 요청은 모니카 핀치 살인 사건을 수사해 달라는 것.  그녀의 남편이자 유명 영화 배우인 앨러스테어 핀치가 유력한 살해 용의자이지만,  아직 드라마 출연분을 채워야 하는 네트워크의 대표인 시고르스키는 그가 혐의를 벗기를 바라고 있다.  로레나에게는 사건을 맡기를 거절했지만,  그가 합류한다는 기사를 보고 갱단 패거리들이 찾아와 그를 협박하고, 설상가상으로 로레나는 행방불명된다.  왈도는 고요했던 은둔 생활을 뒤로 하고, 일을 바로잡으러 시끌벅적한 LA 세상 밖으로 나오게 되는데…",
      popularity: 50.287,
      poster_path: "/brKmmJHmLDdgWNThBgCwgKOBcIk.jpg",
      release_date: "2024-05-08",
      title: "할리우드 살인사건",
      video: false,
      vote_average: 5.885,
      vote_count: 283,
    },
    {
      adult: false,
      backdrop_path: "/9ZcJT3plQQPnYqCRkTBbOSksVX8.jpg",
      genre_ids: [53, 9648],
      id: 743815,
      original_language: "ko",
      original_title: "그녀가 죽었다",
      overview:
        "고객이 맡긴 열쇠로 그 집에 들어가  남의 삶을 훔쳐보는 취미를 지닌 공인중개사 구정태. 편의점 소시지를 먹으며 비건 샐러드 사진을 포스팅하는  SNS 인플루언서 한소라에게 흥미를 느끼고 관찰하기 시작한다. 급기야 한소라의 집까지 드나들던 구정태는 어느 날, 그녀가 소파에 죽은 채 늘어져 있는 모습을 발견하게 된다. 그 후 그가 한소라 집에 들어간 것을 알고 있는 누군가가 협박을 시작하고, 사건을 맡은 강력반 형사 오영주의 수사망이 그를 향해 좁혀온다. 스스로 범인을 찾아야 하는 구정태는 한소라의 SNS를 통해 주변 인물들을 뒤지며 진범을 찾아 나서는데…",
      popularity: 27.073,
      poster_path: "/wTtcvHnO0lzF9qOgmBjjzce2PMy.jpg",
      release_date: "2024-05-15",
      title: "그녀가 죽었다",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/hY97iRKr2t44lbX2GHRhfK5CVC7.jpg",
      genre_ids: [99],
      id: 1004663,
      original_language: "en",
      original_title: "All the Beauty and the Bloodshed",
      overview:
        "전설적인 사진작가 낸 골딘의 삶, 예술, 투쟁, 그리고 생존. 언니가 스스로 목숨을 끊은 후, 사진은 나의 유일한 언어였다. 나는 생생하게 반짝이는 뉴욕에서 죽어가는 친구들의 아름다운 모습을 포착했고, 있는 그대로의 내 얼굴을 솔직하게 담아냈다. 이제는 내 모든 명성을 걸고 거대 제약회사에 맞서 싸운다. 생존과 투쟁의 기록이 담긴 나의 일기장을 당신에게 펼쳐 보인다.",
      popularity: 25.008,
      poster_path: "/fiGdZhBQip33XV8hjgxIqN9OHGR.jpg",
      release_date: "2024-05-15",
      title: "낸 골딘, 모든 아름다움과 유혈사태",
      video: false,
      vote_average: 7.4,
      vote_count: 121,
    },
    {
      adult: false,
      backdrop_path: "/8yugpdDjm0WDAtmkd2ZYNMlDWj3.jpg",
      genre_ids: [18, 10749],
      id: 1114002,
      original_language: "zh",
      original_title: "红色冲浪板",
      overview:
        "서핑 마니아들의 유토피아, 완안은 잘 알려지지 않은 곳이다. 동빈은 바닷가에 서핑용품 가게를 열고 다양한 손님을 맞고 있다. 샤오팡은 과거의 비밀을 숨기고, 위안용은 부모님의 보호를 벗어났으며, 양판은 미지의 세계로 나아갈 방향을 모색한다. 모호하고 진솔한 감정을 터뜨리며, 그들은 희미한 빛으로 서로를 비춘다. 그들의 비밀은 영원히 바다에 잠기게 될까, 아니면 서로의 기억 속에서 다른 버전으로 남게 될까?",
      popularity: 24.937,
      poster_path: "/5f1E66jECGCJvikdmhTzYUEeT2P.jpg",
      release_date: "2024-05-17",
      title: "낭인",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/893hqH2OLQo1Vv0dwHtQmrfP3fT.jpg",
      genre_ids: [10749, 18],
      id: 695932,
      original_language: "ja",
      original_title: "花束みたいな恋をした",
      overview:
        "집으로 가는 막차를 놓친 스물한 살 대학생 `무기`와 `키`는  첫차를 기다리며 함께 시간을 보내게 된다. 좋아하는 책부터 영화, 신고 있는 신발까지 모든 게 꼭 닮은 두 사람은 수줍은 고백과 함께 연애를 시작하고 매일매일 행복한 시간을 쌓아간다.  하지만 대학 졸업과 함께 취업 준비에 나선 두 사람은 점점 서로에게 소원해지고 꿈과 현실 사이의 거리 만큼 마음의 거리도 멀어지기 시작하는데...",
      popularity: 23.909,
      poster_path: "/5ACMKe2YhXB4lXMvRCMD3x0w1kg.jpg",
      release_date: "2021-07-14",
      title: "꽃다발 같은 사랑을 했다",
      video: false,
      vote_average: 7.7,
      vote_count: 70,
    },
  ],
  total_pages: 3,
  total_results: 55,
};
